// ─── Demo inspection data — single source of truth ────────────────────────
// Used by dev/seed-demo.mts (seeds the DB) and dev/export-demo-reports.mts
// (writes a manifest so the actual report PDFs can be generated). All FICTIONAL:
// invented sites, addresses and inspector organisations, NZ construction content,
// failure themes deliberately clustered so the Insights ranking reads well.

export type Item = { cat: string; title: string; detail: string; loc?: string };
export type Insp = {
  doc: string; site: string; source: "council" | "consultant"; code?: string;
  type: string; inspector: string; outcome: "pass" | "partial" | "fail"; daysAgo: number; items: Item[];
};

// re-used item builders (the clustered themes)
export const firestop = (loc: string): Item => ({ cat: "Fire", title: "Passive fire stopping incomplete", detail: "Penetrations through the fire-rated wall not fire-stopped. Seal both sides to the wall FRR and label.", loc });
export const firecollar = (loc: string): Item => ({ cat: "Fire", title: "Fire collar not installed correctly", detail: "Fire collar to the uPVC penetration proud of the slab and fixed one side only. Refit hard to the soffit per the manufacturer detail.", loc });
export const drainfall = (loc: string): Item => ({ cat: "Plumbing & Drainage", title: "Insufficient fall to drainage penetration", detail: "Penetration set out flat; will not achieve the required fall. Reset to maintain gradient to the design.", loc });
export const bracing = (loc: string): Item => ({ cat: "Structural", title: "Bracing fixing incomplete", detail: "Bracing sheet nailing does not match the bracing schedule; several fixings missing at the panel edges.", loc });
export const weather = (loc: string): Item => ({ cat: "Weathertightness / Cladding", title: "Flashing junction not sealed", detail: "Head flashing junction to the cladding left open; no upstand or sealant. Rework to the weathertightness detail.", loc });
export const cable = (loc: string): Item => ({ cat: "Electrical", title: "Cable segregation inadequate", detail: "Power and data cabling run together with no separation; re-run to maintain segregation.", loc });
export const damper = (loc: string): Item => ({ cat: "Mechanical", title: "Fire damper access not provided", detail: "No access panel to the fire damper; provide access for testing and commissioning.", loc });
export const acoustic = (loc: string): Item => ({ cat: "Acoustic", title: "Acoustic seal missing at penetration", detail: "Service penetration through the inter-tenancy wall not acoustically sealed; seal to maintain the STC rating.", loc });

export const INSPECTIONS: Insp[] = [
  // ── Council statutory (mixed outcomes) ──
  { doc: "BCA IPL Post-line Level 1 partial 1", site: "14 Kowhai Lane, Papakura", source: "council", code: "IPL", type: "Post-line", inspector: "Southern Districts Council", outcome: "partial", daysAgo: 120, items: [firestop("L1 · grid C"), bracing("L1 · east wall"), { cat: "Interior / Linings", title: "Ceiling stopping incomplete", detail: "Ceiling stopping not complete at the L1 corridor; complete before line inspection re-book.", loc: "L1 corridor" }] },
  { doc: "BCA IPB Pre-line Level 1 partial 1", site: "14 Kowhai Lane, Papakura", source: "council", code: "IPB", type: "Pre-line", inspector: "Southern Districts Council", outcome: "partial", daysAgo: 128, items: [firestop("L1 · riser"), { cat: "Plumbing & Drainage", title: "Pipe not clipped at required centres", detail: "Hot and cold pipes not clipped to the required centres in the L1 wall; clip before lining.", loc: "L1 wall" }] },
  { doc: "BCA IFG Framing partial 1", site: "14 Kowhai Lane, Papakura", source: "council", code: "IFG", type: "Framing", inspector: "Southern Districts Council", outcome: "partial", daysAgo: 150, items: [bracing("Ground · south wall"), { cat: "Structural", title: "Lintel fixing not per plan", detail: "Lintel over the garage opening not fixed as per the structural detail; add the specified fixings.", loc: "Ground · garage" }] },
  { doc: "BCA ICA Cavity wrap fail 1", site: "14 Kowhai Lane, Papakura", source: "council", code: "ICA", type: "Cavity / wrap", inspector: "Southern Districts Council", outcome: "fail", daysAgo: 140, items: [weather("Level 1 · window heads"), { cat: "Weathertightness / Cladding", title: "Building wrap torn and not lapped", detail: "Wrap torn at several fixings and not lapped over the flashings; repair and re-lap before cladding.", loc: "L1 · north wall" }] },
  { doc: "BCA IPP Plumbing pass 1", site: "14 Kowhai Lane, Papakura", source: "council", code: "IPP", type: "Pre-line plumbing", inspector: "Southern Districts Council", outcome: "pass", daysAgo: 132, items: [] },
  { doc: "BCA IPL Post-line partial 2", site: "27 Rata Street, Hamilton", source: "council", code: "IPL", type: "Post-line", inspector: "Waikato City Council", outcome: "partial", daysAgo: 96, items: [firestop("L2 · grid B"), acoustic("L2 · inter-tenancy wall")] },
  { doc: "BCA IPB Pre-line partial 2", site: "27 Rata Street, Hamilton", source: "council", code: "IPB", type: "Pre-line", inspector: "Waikato City Council", outcome: "partial", daysAgo: 104, items: [firestop("L2 · riser"), drainfall("L2 · wet area")] },
  { doc: "BCA IFG Framing pass 2", site: "27 Rata Street, Hamilton", source: "council", code: "IFG", type: "Framing", inspector: "Waikato City Council", outcome: "pass", daysAgo: 118, items: [] },
  { doc: "BCA ICL Cladding partial 2", site: "27 Rata Street, Hamilton", source: "council", code: "ICL", type: "Cladding", inspector: "Waikato City Council", outcome: "partial", daysAgo: 88, items: [weather("Level 2 · sill flashings"), { cat: "Weathertightness / Cladding", title: "Insufficient ground clearance to cladding", detail: "Cladding finishes below the required clearance to finished ground level at the south elevation; trim to clearance.", loc: "Ground · south" }] },
  { doc: "BCA IDT Drainage partial 2", site: "27 Rata Street, Hamilton", source: "council", code: "IDT", type: "Drainage", inspector: "Waikato City Council", outcome: "partial", daysAgo: 100, items: [drainfall("Site · SW line"), { cat: "Plumbing & Drainage", title: "Inspection point not accessible", detail: "Drainage IP buried and not brought to surface; expose and make accessible.", loc: "Site · east" }] },
  { doc: "BCA IF1 Final residential partial 3", site: "3 Miro Place, Tauranga", source: "council", code: "IF1", type: "Final", inspector: "Bay Building Consents", outcome: "partial", daysAgo: 60, items: [{ cat: "Access & Barriers", title: "Barrier height below F4 minimum", detail: "Balustrade to the L1 balcony measures below the F4 minimum height; raise to comply.", loc: "L1 balcony" }, firecollar("L1 · riser")] },
  { doc: "BCA IPL Post-line fail 3", site: "3 Miro Place, Tauranga", source: "council", code: "IPL", type: "Post-line", inspector: "Bay Building Consents", outcome: "fail", daysAgo: 72, items: [firestop("L1 · grid D"), firecollar("L1 · grid D"), bracing("L1 · west wall")] },
  { doc: "BCA IPB Pre-line partial 3", site: "3 Miro Place, Tauranga", source: "council", code: "IPB", type: "Pre-line", inspector: "Bay Building Consents", outcome: "partial", daysAgo: 80, items: [drainfall("L1 · bathroom"), cable("L1 · wall")] },
  { doc: "BCA ISF Slab pass 4", site: "88 Totara Ave, Auckland", source: "council", code: "ISF", type: "Slab / floor", inspector: "Auckland Council", outcome: "pass", daysAgo: 175, items: [] },

  // ── Fire consultant reports (passive-fire heavy) ──
  { doc: "Fire observation report 01", site: "88 Totara Ave, Auckland", source: "consultant", type: "Fire", inspector: "Kahikatea Fire Engineering", outcome: "partial", daysAgo: 55, items: [firestop("Basement · riser"), firecollar("Basement · grid A"), firestop("Basement · grid C")] },
  { doc: "Fire observation report 02", site: "88 Totara Ave, Auckland", source: "consultant", type: "Fire", inspector: "Kahikatea Fire Engineering", outcome: "partial", daysAgo: 48, items: [firestop("L1 · corridor"), { cat: "Fire", title: "Fire door gap exceeds tolerance", detail: "Perimeter gap to the L1 fire door exceeds the tested tolerance; adjust the door and stops.", loc: "L1 · corridor" }] },
  { doc: "Fire observation report 03", site: "88 Totara Ave, Auckland", source: "consultant", type: "Fire", inspector: "Kahikatea Fire Engineering", outcome: "partial", daysAgo: 40, items: [firecollar("L2 · riser"), firestop("L2 · grid B")] },
  { doc: "Fire observation report 04", site: "42 Manuka Rd, Auckland", source: "consultant", type: "Fire", inspector: "Kahikatea Fire Engineering", outcome: "partial", daysAgo: 33, items: [firestop("L3 · riser"), { cat: "Fire", title: "Intumescent sealant missing at pipe penetration", detail: "Annular gap at the 65mm penetration has no sealant; seal both sides and label.", loc: "L3 · riser" }] },
  { doc: "Fire observation report 05", site: "42 Manuka Rd, Auckland", source: "consultant", type: "Fire", inspector: "Kahikatea Fire Engineering", outcome: "partial", daysAgo: 26, items: [firestop("L4 · grid C"), firecollar("L4 · grid C")] },
  { doc: "Fire observation report 06", site: "42 Manuka Rd, Auckland", source: "consultant", type: "Fire", inspector: "Kahikatea Fire Engineering", outcome: "partial", daysAgo: 18, items: [firestop("Basement car park · grid F"), acoustic("L2 · inter-tenancy")] },

  // ── Hydraulic (drainage theme) ──
  { doc: "Hydraulic observation report 01", site: "27 Rata Street, Hamilton", source: "consultant", type: "Hydraulic", inspector: "Downpipe Consulting", outcome: "partial", daysAgo: 58, items: [drainfall("Basement · plant room"), { cat: "Plumbing & Drainage", title: "Tundish missing", detail: "Ø100mm tundish not installed at the plant room; confirm and install.", loc: "Basement · plant room" }] },
  { doc: "Hydraulic observation report 02", site: "27 Rata Street, Hamilton", source: "consultant", type: "Hydraulic", inspector: "Downpipe Consulting", outcome: "partial", daysAgo: 44, items: [drainfall("L1 · wet areas"), drainfall("L2 · wet areas")] },
  { doc: "Hydraulic observation report 03", site: "3 Miro Place, Tauranga", source: "consultant", type: "Hydraulic", inspector: "Downpipe Consulting", outcome: "partial", daysAgo: 31, items: [{ cat: "Plumbing & Drainage", title: "Penetration sleeves not installed", detail: "Sleeves for the drainage penetrations not installed before the pour; core-drill and make good.", loc: "L1 · slab" }, drainfall("L1 · shower")] },
  { doc: "Hydraulic observation report 04", site: "3 Miro Place, Tauranga", source: "consultant", type: "Hydraulic", inspector: "Downpipe Consulting", outcome: "partial", daysAgo: 20, items: [drainfall("Site · stormwater")] },

  // ── Structural (bracing/fixing) ──
  { doc: "Structural observation report 01", site: "88 Totara Ave, Auckland", source: "consultant", type: "Structural", inspector: "Totara Structural Consultants", outcome: "partial", daysAgo: 62, items: [bracing("Ground · grid 3"), { cat: "Structural", title: "Hold-down bolts not tightened", detail: "Hold-down bolts to the ground-floor bracing not tightened to spec; torque and mark.", loc: "Ground · grid 3" }] },
  { doc: "Structural observation report 02", site: "42 Manuka Rd, Auckland", source: "consultant", type: "Structural", inspector: "Totara Structural Consultants", outcome: "partial", daysAgo: 46, items: [bracing("L1 · grid B"), { cat: "Structural", title: "Beam bearing insufficient", detail: "Transfer beam bearing at grid B less than detailed; provide the specified bearing length.", loc: "L1 · grid B" }] },
  { doc: "Structural observation report 03", site: "42 Manuka Rd, Auckland", source: "consultant", type: "Structural", inspector: "Totara Structural Consultants", outcome: "partial", daysAgo: 28, items: [bracing("L2 · grid D")] },

  // ── Mechanical (duct/damper) ──
  { doc: "Mechanical observation report 01", site: "88 Totara Ave, Auckland", source: "consultant", type: "Mechanical", inspector: "AirCell Consulting", outcome: "partial", daysAgo: 52, items: [damper("L1 · corridor"), { cat: "Mechanical", title: "Duct support spacing exceeds spec", detail: "Supply duct supports spaced beyond the specified maximum; add supports.", loc: "L1 · ceiling" }] },
  { doc: "Mechanical observation report 02", site: "88 Totara Ave, Auckland", source: "consultant", type: "Mechanical", inspector: "AirCell Consulting", outcome: "partial", daysAgo: 36, items: [damper("L2 · corridor")] },
  { doc: "Mechanical observation report 03", site: "42 Manuka Rd, Auckland", source: "consultant", type: "Mechanical", inspector: "AirCell Consulting", outcome: "partial", daysAgo: 22, items: [damper("L3 · corridor"), { cat: "Mechanical", title: "Flexible duct length excessive", detail: "Flexible duct to the L3 diffusers exceeds the maximum length; shorten and support.", loc: "L3 · ceiling" }] },

  // ── Electrical (cable segregation) ──
  { doc: "Electrical observation report 01", site: "27 Rata Street, Hamilton", source: "consultant", type: "Electrical", inspector: "Voltway Electrical Design", outcome: "partial", daysAgo: 50, items: [cable("L1 · riser"), { cat: "Electrical", title: "Cable tray not earthed", detail: "Cable tray section in the L1 riser not bonded; provide earth continuity.", loc: "L1 · riser" }] },
  { doc: "Electrical observation report 02", site: "27 Rata Street, Hamilton", source: "consultant", type: "Electrical", inspector: "Voltway Electrical Design", outcome: "partial", daysAgo: 34, items: [cable("L2 · ceiling")] },
  { doc: "Electrical observation report 03", site: "3 Miro Place, Tauranga", source: "consultant", type: "Electrical", inspector: "Voltway Electrical Design", outcome: "partial", daysAgo: 19, items: [cable("Basement · switch room"), { cat: "Electrical", title: "Penetration not fire-stopped", detail: "Cable penetration through the switch room wall not fire-stopped; seal to the wall FRR.", loc: "Basement · switch room" }] },

  // ── one-off variety ──
  { doc: "Acoustic observation report 01", site: "27 Rata Street, Hamilton", source: "consultant", type: "Acoustic", inspector: "Quietline Acoustics", outcome: "partial", daysAgo: 38, items: [acoustic("L2 · inter-tenancy"), acoustic("L3 · inter-tenancy")] },
  { doc: "Seismic observation report 01", site: "88 Totara Ave, Auckland", source: "consultant", type: "Seismic", inspector: "Totara Structural Consultants", outcome: "partial", daysAgo: 42, items: [{ cat: "Seismic", title: "Ceiling seismic bracing missing", detail: "Suspended ceiling in the L1 lobby has no seismic bracing; brace per the ceiling design.", loc: "L1 lobby" }, { cat: "Seismic", title: "Services restraint not installed", detail: "Large-diameter pipe runs not seismically restrained; add restraints at required centres.", loc: "Basement" }] },
  { doc: "Architectural observation report 01", site: "42 Manuka Rd, Auckland", source: "consultant", type: "Architectural", inspector: "Aria Architects", outcome: "partial", daysAgo: 30, items: [weather("L5 · balcony threshold"), { cat: "Interior / Linings", title: "Wet area substrate not suitable", detail: "Standard plasterboard used behind the shower instead of the specified wet-area board; replace.", loc: "L2 · bathroom" }] },
];
